// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPJDkuQixRLbuUj7cOs-4KeFnIVPQqFgQ',
    appId: '1:701831743759:android:0c20951332fad1cd18967a',
    messagingSenderId: '701831743759',
    projectId: 'pro2-9f0c0',
    storageBucket: 'pro2-9f0c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJDk6I-fmZ4D8Rl-_N-DK5-ge1L-PaASs',
    appId: '1:701831743759:ios:3c0a8a3836530ebd18967a',
    messagingSenderId: '701831743759',
    projectId: 'pro2-9f0c0',
    storageBucket: 'pro2-9f0c0.appspot.com',
    iosBundleId: 'com.example.flutterP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJDk6I-fmZ4D8Rl-_N-DK5-ge1L-PaASs',
    appId: '1:701831743759:ios:3c0a8a3836530ebd18967a',
    messagingSenderId: '701831743759',
    projectId: 'pro2-9f0c0',
    storageBucket: 'pro2-9f0c0.appspot.com',
    iosBundleId: 'com.example.flutterP2',
  );
}
